from Core.DownloadData.DownloadDataController import DownloadDataController
from Core.DataStorage.DataStorageController import DataStorageController

#downloadDataController = DownloadDataController()
#downloadDataController.downloadDataExportImportFull()

dataStorageController = DataStorageController()
dataStorageController.dataStorageServiceExport()