{
 "title": "Desafio em Análise de Dados da SeuBoné",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 3 produtos mais importados por estado nos anos de 2020 e 2021",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "WITH import_ranked AS (\r\n    SELECT \r\n        estado_destino,\r\n        codigo_ncm,\r\n        SUM(valor_mercadoria) AS total_importado,\r\n        ROW_NUMBER() OVER (PARTITION BY estado_destino ORDER BY SUM(valor_mercadoria) DESC) AS rank\r\n    FROM tb_import\r\n    WHERE codigo_ano IN (2020, 2021)\r\n    GROUP BY estado_destino, codigo_ncm\r\n)\r\nSELECT *\r\nFROM import_ranked\r\nWHERE rank <= 3;\r\n"
    }
   ]
  },
  {
   "title": "Top 3 produtos mais exportados por estado nos anos de 2020 e 2021",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "WITH export_ranked AS (\r\n    SELECT \r\n        estado_origem,\r\n        codigo_ncm,\r\n        SUM(valor_mercadoria) AS total_exportado,\r\n        ROW_NUMBER() OVER (\r\n            PARTITION BY estado_origem\r\n            ORDER BY SUM(valor_mercadoria) DESC\r\n        ) AS rank\r\n    FROM tb_export\r\n    WHERE codigo_ano IN (2020, 2021)\r\n    GROUP BY estado_origem, codigo_ncm\r\n)\r\nSELECT *\r\nFROM export_ranked\r\nWHERE rank <= 3;\r\n"
    }
   ]
  },
  {
   "title": "Top 3 produtos exportados em cada mês de 2021 por estado",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "WITH export_ranked AS (\r\n    SELECT \r\n        estado_origem,\r\n        codigo_mes,\r\n        codigo_ncm,\r\n        SUM(valor_mercadoria) AS total_exportado,\r\n        ROW_NUMBER() OVER (\r\n            PARTITION BY estado_origem, codigo_mes\r\n            ORDER BY SUM(valor_mercadoria) DESC\r\n        ) AS rank\r\n    FROM tb_export\r\n    WHERE codigo_ano = 2021\r\n    GROUP BY estado_origem, codigo_mes, codigo_ncm\r\n)\r\nSELECT *\r\nFROM export_ranked\r\nWHERE rank <= 3;\r\n"
    }
   ]
  }
 ]
}